n_workers: 4
# for chunksie estimation
chunksize_time_step: 0.002 # computational time increase for reducing chunksize
chunksize_time_min: 0.004  # minimum computational time for use of parallel computation
GPU: False

use_spectral_gap: True

lambda: 0
cutoff: 0.99999999
with_weights: False

#clustering_mode: 'threshold'
#perturb: 0.01
#n_samples: 10
#log_time: True

clustering_mode: 'signed_modularity'
n_runs: 150  # number of Louvain runs

# additional parameters
save_qualities: True
compute_mutual_information: True
n_partitions: 50  # number of louvian runs for MI computation
compute_ttprime: True
apply_postprocessing: True
