clustering_mode: 'signed_modularity'
n_runs: 200  # number of Louvain runs

# additional parameters
save_qualities: True
compute_mutual_information: True
n_partitions: 50  # number of louvian runs for MI computation
compute_ttprime: True
apply_postprocessing: False
